#!/bin/bash
app=ajenti_docker

path=$(sudo yunohost app setting $app path)
domain=$(sudo yunohost app setting $app domain)
containername=${path#/}

# REmove container
sudo python remove_container.py $app $containername

# Remove nginx configuration
sudo rm /etc/nginx/conf.d/$domain.d/$containername.conf

# Remove containert
sudo rm -rf /home/yunohost.docker/container-$app/config

# Reload
sudo service nginx reload
sudo yunohost app ssowatconf 
